### ISSUE TITLE
Some reqs missing

### ISSUE THREAD

**Issue by Sosnowsky** [uit-cosmo/2d_propagating_blobs#2]
When cloning and pip installing the requirements I get the following missing modules for examples/analyse_output.py.

ModuleNotFoundError: No module named 'netCDF4'
ModuleNotFoundError: No module named 'scipy'

Not sure if this is expected

**Comment by gregordecristoforo** [comment]
scipy and pytest is added to setup.py

I can't reproduce the netCDF issue. The package doesn't require netCDF4

**Comment by Sosnowsky** [comment]
Solved
